### ISSUE TITLE
Consider to implement print_hex func

### ISSUE THREAD

**Issue by dreamIIx** [dreamIIx/unos#1]
## Purpose, reason:
Maybe it will be useful

**Comment by QQ3646** [comment]
ахахахах, 
"Purpose, reason: _"
Думаю изучу этот вопросик j4f, напишу вывод какой-нибудь

**Comment by dreamIIx** [comment]
@QQ3646, вообще говоря решено. Только не в asm'е. Ты же написал на C

**Comment by dreamIIx** [comment]
a515f61

**Comment by QQ3646** [comment]
Ну так а надо было-то на asm'е. На си как-то даже не интересно. Но раз уж такой функционал имеется, то можно закрывать.
